# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message2Server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import MessageType_pb2 as MessageType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14Message2Server.proto\x12\x08protobuf\x1a\x11MessageType.proto\"\r\n\x0bNullRequest\"+\n\x05IDMsg\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12\x0f\n\x07team_id\x18\x02 \x01(\x03\"V\n\tPlayerMsg\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12\x0f\n\x07team_id\x18\x02 \x01(\x03\x12%\n\tship_type\x18\x03 \x01(\x0e\x32\x12.protobuf.ShipType\"Z\n\x07MoveMsg\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12\r\n\x05\x61ngle\x18\x02 \x01(\x01\x12\x1c\n\x14time_in_milliseconds\x18\x03 \x01(\x03\x12\x0f\n\x07team_id\x18\x04 \x01(\x03\"\x80\x01\n\x07SendMsg\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12\x14\n\x0cto_player_id\x18\x02 \x01(\x03\x12\x16\n\x0ctext_message\x18\x03 \x01(\tH\x00\x12\x18\n\x0e\x62inary_message\x18\x04 \x01(\x0cH\x00\x12\x0f\n\x07team_id\x18\x05 \x01(\x03\x42\t\n\x07message\">\n\tAttackMsg\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12\r\n\x05\x61ngle\x18\x02 \x01(\x01\x12\x0f\n\x07team_id\x18\x03 \x01(\x03\"i\n\x0c\x43onstructMsg\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12\x35\n\x11\x63onstruction_type\x18\x02 \x01(\x0e\x32\x1a.protobuf.ConstructionType\x12\x0f\n\x07team_id\x18\x03 \x01(\x03\"A\n\nRecoverMsg\x12\x11\n\tplayer_id\x18\x01 \x01(\x03\x12\x0f\n\x07recover\x18\x02 \x01(\x03\x12\x0f\n\x07team_id\x18\x03 \x01(\x03\"[\n\nInstallMsg\x12)\n\x0bmodule_type\x18\x01 \x01(\x0e\x32\x14.protobuf.ModuleType\x12\x11\n\tplayer_id\x18\x02 \x01(\x03\x12\x0f\n\x07team_id\x18\x03 \x01(\x03\"`\n\x0c\x42uildShipMsg\x12%\n\tship_type\x18\x01 \x01(\x0e\x32\x12.protobuf.ShipType\x12\x0f\n\x07team_id\x18\x02 \x01(\x03\x12\x18\n\x10\x62irthpoint_index\x18\x03 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Message2Server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NULLREQUEST._serialized_start=53
  _NULLREQUEST._serialized_end=66
  _IDMSG._serialized_start=68
  _IDMSG._serialized_end=111
  _PLAYERMSG._serialized_start=113
  _PLAYERMSG._serialized_end=199
  _MOVEMSG._serialized_start=201
  _MOVEMSG._serialized_end=291
  _SENDMSG._serialized_start=294
  _SENDMSG._serialized_end=422
  _ATTACKMSG._serialized_start=424
  _ATTACKMSG._serialized_end=486
  _CONSTRUCTMSG._serialized_start=488
  _CONSTRUCTMSG._serialized_end=593
  _RECOVERMSG._serialized_start=595
  _RECOVERMSG._serialized_end=660
  _INSTALLMSG._serialized_start=662
  _INSTALLMSG._serialized_end=753
  _BUILDSHIPMSG._serialized_start=755
  _BUILDSHIPMSG._serialized_end=851
# @@protoc_insertion_point(module_scope)
